Add terraform modules and environments support

diff --git a/.github/workflows/tf-deploy.yml b/.github/workflows/tf-deploy.yml
--- a/.github/workflows/tf-deploy.yml
+++ b/.github/workflows/tf-deploy.yml
@@ -17,6 +17,7 @@ on:
         options:
           - Development
           - Testing
+          - Production
 
 permissions:
   id-token: write
@@ -59,7 +60,11 @@ jobs:
 
       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
       - name: Terraform Init
-        run: terraform init
+        run: terraform init  \
+          -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP }}" \
+          -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT }}" \
+          -backend-config="container_name=${{ secrets.BACKEND_CONTAINER_NAME }}" \
+          -backend-config="key=${{ secrets.BACKEND_STATE_FILE }}"
 
       # Checks that all Terraform configuration files adhere to a canonical format
       # Will fail the build if not
@@ -73,7 +78,7 @@ jobs:
         run: |
           export exitcode=0
 
-          terraform plan -var="admin_password=${{ secrets.DB_PASSWORD }}" -detailed-exitcode -no-color -out=tfplan || exitcode=$?  # Capture the exit code immediately
+          terraform plan -var="admin_password=${{ secrets.DB_PASSWORD }}" -detailed-exitcode -no-color -var-file=environments/${{ github.event.inputs.environment }}/terraform.tfvars -out=tfplan || exitcode=$?  # Capture the exit code immediately
 
           echo "Terraform Plan exit code: $exitcode"
 
@@ -173,7 +178,11 @@ jobs:
 
       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
       - name: Terraform Init
-        run: terraform init
+        run: terraform init \
+          -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP }}" \
+          -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT }}" \
+          -backend-config="container_name=${{ secrets.BACKEND_CONTAINER_NAME }}" \
+          -backend-config="key=${{ secrets.BACKEND_STATE_FILE }}"
 
       # Download saved plan from artifacts  
       - name: Download Terraform Plan
