Use -var options instead of TF_VAR variables

diff --git a/.github/workflows/tf-deploy.yml b/.github/workflows/tf-deploy.yml
--- a/.github/workflows/tf-deploy.yml
+++ b/.github/workflows/tf-deploy.yml
@@ -80,15 +80,19 @@ jobs:
       - name: Terraform Plan
         id: tf-plan-step
         run: |
-          export TF_VAR_admin_password="${{ secrets.DB_PASSWORD }}"
-          export TF_VAR_resource_group_name="${{ vars.RESOURCE_GROUP }}"
-          export TF_VAR_naming_prefix="${{ vars.NAMING_PREFIX }}"
+          #export TF_VAR_admin_password="${{ secrets.DB_PASSWORD }}"
+          #export TF_VAR_resource_group_name="${{ vars.RESOURCE_GROUP }}"
+          #export TF_VAR_naming_prefix="${{ vars.NAMING_PREFIX }}"
 
           export exitcode=0
 
           terraform -chdir=environments/${{ env.ENVIRONMENT }} plan \
             -detailed-exitcode -no-color \
-            -var-file=terraform.tfvars -out=tfplan || exitcode=$?  # Capture the exit code immediately
+            -var-file=terraform.tfvars \
+            -var="admin_password=${{ secrets.DB_PASSWORD }}" \
+            -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
+            -var="naming_prefix=${{ vars.NAMING_PREFIX }}" \
+            -out=tfplan || exitcode=$?  # Capture the exit code immediately
 
           echo "Terraform Plan exit code: $exitcode"
 
