Put Checkov check in comments for now

diff --git a/.github/workflows/tf-unit-tests.yml b/.github/workflows/tf-unit-tests.yml
--- a/.github/workflows/tf-unit-tests.yml
+++ b/.github/workflows/tf-unit-tests.yml
@@ -26,25 +26,29 @@ jobs:
     - name: Terraform Init
       run: terraform init -backend=false
 
-    # Validate terraform files
-    - name: Terraform Validate
-      run: terraform validate
-
     # Checks that all Terraform configuration files adhere to a canonical format
     - name: Terraform Format
       run: terraform fmt -check -recursive
-    
+
+    # Validate terraform files
+    - name: Terraform Validate
+      run: terraform validate
+          
+    # Run Terraform Plan (Preview Changes)
+    - name: Terraform Plan
+      run: terraform plan -out=tfplan
+
     # Perform a security scan of the terraform code using checkov
-    - name: Run Checkov action
-      id: checkov
-      uses: bridgecrewio/checkov-action@master
-      with: 
-        framework: terraform
+    #- name: Run Checkov action
+    #  id: checkov
+    #  uses: bridgecrewio/checkov-action@master
+    #  with: 
+    #    framework: terraform
 
     # Upload results to GitHub Advanced Security
-    - name: Upload SARIF file
-      if: success() || failure()
-      uses: github/codeql-action/upload-sarif@v3
-      with:
-        sarif_file: results.sarif
-        category: checkov
+    #- name: Upload SARIF file
+    #  if: success() || failure()
+    #  uses: github/codeql-action/upload-sarif@v3
+    #  with:
+    #    sarif_file: results.sarif
+    #    category: checkov
